"""Finite-temperature configurational contributions for oxygen vacancies.

This module augments the static-lattice vacancy analysis without changing the
underlying 0 K relaxed energies.  Three solid configurational treatments are
supported:

``none``
    No solid configurational contribution.
``ideal``
    Ideal occupied/vacant oxygen-site mixing entropy.
``configurational``
    A canonical partition function over the symmetry-distinct vacancy
    configurations generated by the workflow. Exact orbit degeneracies are
    required. When every exact orbit was relaxed, relaxed energies are used;
    otherwise the complete exact-enumeration single-point spectrum supplies a
    configurational correction relative to its own minimum, which is added to
    the relaxed static minimum for the vacancy count.

The partition-function mode counts only oxygen-vacancy arrangements for the
selected source parent. It does not add dopant-configurational entropy or solid
vibrational/electronic/magnetic free-energy terms.
"""

from __future__ import annotations

import csv
import json
import math
from pathlib import Path
from typing import Any, Sequence

from dopingflow.vacancy_analysis import (
    K_B_EV_PER_K,
    NEGLECTED_SOLID_TERMS,
    NIST_O2_SHOMATE_SOURCE,
    nist_o2_standard_state_delta_mu_eV_per_O,
    oxygen_pressure_delta_mu_eV_per_O,
    oxygen_standard_state_delta_mu,
)

_KJ_PER_MOL_PER_EV = 96.4853321233
_O2_H298_MINUS_H0_KJ_PER_MOL = 8.683
_O_H298_MINUS_H0_EV = _O2_H298_MINUS_H0_KJ_PER_MOL / (2.0 * _KJ_PER_MOL_PER_EV)


def _as_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    return str(value).strip().lower() in {"1", "true", "yes", "y"}


def _safe_float(value: Any) -> float | None:
    if value is None or value == "":
        return None
    try:
        result = float(value)
    except (TypeError, ValueError):
        return None
    return result if math.isfinite(result) else None


def _json_dict(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return value
    if value in {None, ""}:
        return {}
    try:
        parsed = json.loads(str(value))
    except (TypeError, json.JSONDecodeError):
        return {}
    return parsed if isinstance(parsed, dict) else {}


def _composition_identity(row: dict[str, Any]) -> tuple[tuple[tuple[str, int], ...], int]:
    counts = _json_dict(row.get("dopant_counts_json") or row.get("dopant_counts_from_parent"))
    normalized = tuple(sorted((str(key), int(value)) for key, value in counts.items()))
    return normalized, int(row.get("n_total_cations", 0))


def ideal_vacancy_configurational_entropy_eV_per_K(
    n_vacancies: int, n_oxygen_sites: int
) -> float:
    """Return ideal occupied/vacant-site mixing entropy in eV/K."""
    n_vacancies = int(n_vacancies)
    n_oxygen_sites = int(n_oxygen_sites)
    if n_oxygen_sites <= 0:
        raise ValueError("n_oxygen_sites must be > 0")
    if n_vacancies < 0 or n_vacancies > n_oxygen_sites:
        raise ValueError("n_vacancies must satisfy 0 <= n_vacancies <= n_oxygen_sites")
    if n_vacancies in {0, n_oxygen_sites}:
        return 0.0
    fraction = n_vacancies / n_oxygen_sites
    return -K_B_EV_PER_K * n_oxygen_sites * (
        fraction * math.log(fraction)
        + (1.0 - fraction) * math.log(1.0 - fraction)
    )


def _logsumexp(values: Sequence[float]) -> float:
    if not values:
        raise ValueError("logsumexp requires at least one value")
    maximum = max(values)
    return maximum + math.log(sum(math.exp(value - maximum) for value in values))


def configurational_partition_thermodynamics(
    rows: Sequence[dict[str, Any]],
    minimum_row: dict[str, Any],
    temperature_K: float,
    *,
    exclude_unconverged: bool = True,
) -> dict[str, Any]:
    """Evaluate the exact-orbit vacancy configurational partition function.

    The source parent is fixed to the parent that supplies the static minimum
    for this vacancy count. This avoids combining independent dopant/parent
    structures as if they were vacancy microstates of one lattice.
    """
    temperature_K = float(temperature_K)
    if temperature_K <= 0:
        raise ValueError("temperature_K must be > 0 for configurational thermodynamics")

    n_vacancies = int(minimum_row["n_vacancies"])
    if n_vacancies == 0:
        return {
            "free_energy_correction_eV": 0.0,
            "entropy_eV_per_K": 0.0,
            "mean_relative_energy_eV": 0.0,
            "partition_log_Z_relative": 0.0,
            "partition_orbit_count": 1,
            "partition_total_degeneracy": 1,
            "partition_exact": True,
            "partition_energy_basis": "parent_reference",
        }

    identity = _composition_identity(minimum_row)
    source_parent = str(minimum_row.get("source_parent_id", ""))
    candidates = [
        dict(row)
        for row in rows
        if int(row.get("n_vacancies", -1)) == n_vacancies
        and str(row.get("parent_id", "")) == source_parent
        and _composition_identity(dict(row)) == identity
    ]
    if not candidates:
        raise ValueError(
            "Configurational entropy requested but no vacancy configurations were found "
            f"for {minimum_row.get('actual_composition_key')} with n={n_vacancies} "
            f"from source parent {source_parent!r}."
        )

    non_exact = [
        row
        for row in candidates
        if str(row.get("enumeration_mode", "")).strip().lower() != "exact"
        or not _as_bool(row.get("degeneracy_is_exact", False))
        or int(row.get("degeneracy") or 0) <= 0
    ]
    if non_exact:
        raise ValueError(
            "solid_configurational_entropy='configurational' requires exact vacancy "
            "enumeration with exact symmetry-orbit degeneracies for every configuration. "
            f"The source parent {source_parent!r}, n={n_vacancies} contains sampled or "
            "non-exact rows. Use enumeration_mode='exact' (with sufficiently large exact "
            "limits) or choose solid_configurational_entropy='ideal'."
        )

    relaxed_energies: list[float] = []
    relaxed_complete = True
    for row in candidates:
        energy = _safe_float(row.get("energy_relaxed_total_eV"))
        converged_ok = (not exclude_unconverged) or _as_bool(row.get("converged", False))
        if energy is None or not converged_ok:
            relaxed_complete = False
            break
        relaxed_energies.append(energy)

    if relaxed_complete:
        energies = relaxed_energies
        energy_basis = "complete_exact_relaxed_spectrum"
    else:
        energies = []
        for row in candidates:
            energy = _safe_float(row.get("energy_sp_total_eV"))
            if energy is None:
                raise ValueError(
                    "Configurational partition function requires a complete exact energy "
                    f"spectrum, but {source_parent!r}, n={n_vacancies} has a row without "
                    "energy_sp_total_eV."
                )
            energies.append(energy)
        energy_basis = "complete_exact_single_point_spectrum_correction_to_relaxed_minimum"

    minimum_energy = min(energies)
    relative_energies = [energy - minimum_energy for energy in energies]
    beta = 1.0 / (K_B_EV_PER_K * temperature_K)
    log_weights = [
        math.log(int(row["degeneracy"])) - beta * relative
        for row, relative in zip(candidates, relative_energies)
    ]
    log_z = _logsumexp(log_weights)
    probabilities = [math.exp(value - log_z) for value in log_weights]
    mean_relative_energy = sum(
        probability * relative
        for probability, relative in zip(probabilities, relative_energies)
    )
    free_energy_correction = -K_B_EV_PER_K * temperature_K * log_z
    entropy = (mean_relative_energy - free_energy_correction) / temperature_K

    return {
        "free_energy_correction_eV": free_energy_correction,
        "entropy_eV_per_K": entropy,
        "mean_relative_energy_eV": mean_relative_energy,
        "partition_log_Z_relative": log_z,
        "partition_orbit_count": len(candidates),
        "partition_total_degeneracy": sum(int(row["degeneracy"]) for row in candidates),
        "partition_exact": True,
        "partition_energy_basis": energy_basis,
    }


def solid_configurational_thermodynamics(
    mode: str,
    rows: Sequence[dict[str, Any]],
    minimum_row: dict[str, Any],
    temperature_K: float,
    *,
    exclude_unconverged: bool = True,
) -> dict[str, Any]:
    """Return the selected solid configurational contribution for one count."""
    mode = str(mode).strip().lower()
    n_vacancies = int(minimum_row["n_vacancies"])
    if mode == "none":
        return {
            "free_energy_correction_eV": 0.0,
            "entropy_eV_per_K": 0.0,
            "mean_relative_energy_eV": 0.0,
            "partition_log_Z_relative": 0.0,
            "partition_orbit_count": None,
            "partition_total_degeneracy": None,
            "partition_exact": None,
            "partition_energy_basis": "none",
        }
    if mode == "ideal":
        n_sites = int(minimum_row.get("n_oxygen_sites_parent", 0))
        entropy = ideal_vacancy_configurational_entropy_eV_per_K(n_vacancies, n_sites)
        return {
            "free_energy_correction_eV": -float(temperature_K) * entropy,
            "entropy_eV_per_K": entropy,
            "mean_relative_energy_eV": None,
            "partition_log_Z_relative": None,
            "partition_orbit_count": None,
            "partition_total_degeneracy": math.comb(n_sites, n_vacancies),
            "partition_exact": False,
            "partition_energy_basis": "ideal_random_mixing",
        }
    if mode == "configurational":
        return configurational_partition_thermodynamics(
            rows,
            minimum_row,
            temperature_K,
            exclude_unconverged=exclude_unconverged,
        )
    raise ValueError(
        "solid_configurational_entropy must be one of: none, ideal, configurational"
    )


def _pressure_grid(cfg: Any) -> list[float]:
    count = int(
        math.floor(
            (float(cfg.log10_pO2_max_bar) - float(cfg.log10_pO2_min_bar))
            / float(cfg.log10_pO2_step)
            + 1.0e-12
        )
    )
    values = [
        float(cfg.log10_pO2_min_bar) + index * float(cfg.log10_pO2_step)
        for index in range(count + 1)
    ]
    if not values or values[-1] < float(cfg.log10_pO2_max_bar) - 1.0e-10:
        values.append(float(cfg.log10_pO2_max_bar))
    return values


def _standard_state_delta_mu(cfg: Any, temperature_K: float, *, calibrated: bool) -> float:
    if calibrated and cfg.oxygen_standard_state_mode == "nist_shomate":
        return (
            nist_o2_standard_state_delta_mu_eV_per_O(temperature_K)
            - _O_H298_MINUS_H0_EV
        )
    return oxygen_standard_state_delta_mu(cfg, temperature_K)


def _tied_counts(values: dict[int, float], tolerance: float) -> list[int]:
    minimum = min(values.values())
    return sorted(
        n_vacancies
        for n_vacancies, value in values.items()
        if abs(value - minimum) <= tolerance
    )


def _write_csv(path: Path, rows: Sequence[dict[str, Any]]) -> None:
    fields = sorted({key for row in rows for key in row})
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow(
                {
                    key: json.dumps(value, sort_keys=True)
                    if isinstance(value, (dict, list))
                    else value
                    for key, value in row.items()
                }
            )


def _write_pair(
    parent_root: Path, stem: str, rows: Sequence[dict[str, Any]]
) -> tuple[Path, Path]:
    csv_path = parent_root / f"{stem}.csv"
    json_path = parent_root / f"{stem}.json"
    _write_csv(csv_path, rows)
    json_path.write_text(json.dumps(list(rows), indent=2, sort_keys=True), encoding="utf-8")
    return csv_path, json_path


def _approximation_text(mode: str) -> str:
    if mode == "configurational":
        return (
            "Finite-T screening uses 0 K relaxed ML minima plus an oxygen-vacancy "
            "configurational partition-function correction from exact symmetry orbits; "
            "the complete relaxed spectrum is used when available, otherwise the complete "
            "exact single-point spectrum supplies the configurational correction. Solid "
            "vibrational, zero-point, thermal-electronic, magnetic, anharmonic, thermal-"
            "expansion and pV terms are neglected."
        )
    if mode == "ideal":
        return (
            "Finite-T screening uses 0 K relaxed ML minima plus ideal occupied/vacant "
            "oxygen-site mixing entropy. Solid vibrational, zero-point, thermal-electronic, "
            "magnetic, anharmonic, thermal-expansion and pV terms are neglected."
        )
    return (
        "Static-lattice finite-T screening uses 0 K relaxed ML minima. Solid vibrational, "
        "zero-point, configurational, thermal-electronic, magnetic, anharmonic, thermal-"
        "expansion and pV terms are neglected."
    )


def augment_vacancy_formation_free_energy(
    *,
    outputs: dict[str, Path],
    rows: Sequence[dict[str, Any]],
    cfg: Any,
    parent_root: Path,
    calibrated_reference: bool,
) -> dict[str, Path]:
    """Write finite-T vacancy formation free energies and entropy-aware T-pO2 stability.

    The existing T-independent ``delta_mu_O`` intervals are deliberately left
    unchanged: they remain static-lattice quantities. The new table reports the
    actual finite-temperature formation free energy for every vacancy count on
    the requested T-pO2 grid.
    """
    minima_path = outputs.get("vacancy_static_minima_json")
    if minima_path is None or not minima_path.exists():
        return outputs
    minima: list[dict[str, Any]] = json.loads(minima_path.read_text(encoding="utf-8"))
    if not minima:
        return outputs

    mode = str(getattr(cfg, "solid_configurational_entropy", "none")).strip().lower()
    approximation = _approximation_text(mode)
    for line in minima:
        line["solid_configurational_entropy_mode"] = mode
        line["finite_temperature_configurational_treatment"] = mode
        if mode != "none":
            line["static_lattice_approximation"] = approximation
        if mode == "ideal":
            n_sites = int(line.get("n_oxygen_sites_parent", 0))
            line["solid_configurational_entropy_eV_per_K"] = (
                ideal_vacancy_configurational_entropy_eV_per_K(
                    int(line["n_vacancies"]), n_sites
                )
                if n_sites > 0
                else 0.0
            )
        elif mode == "configurational":
            # The partition-function entropy depends on T and is reported in
            # the finite-temperature table/pressure map rather than as one
            # temperature-independent number on the static minima.
            line["solid_configurational_entropy_eV_per_K"] = None

    # Keep the compact and explicitly named static minima synchronized.
    for stem in ("vacancy_minima_by_composition", "vacancy_static_minima"):
        csv_path, json_path = _write_pair(parent_root, stem, minima)
        outputs[f"{stem}_csv"] = csv_path
        outputs[f"{stem}_json"] = json_path

    if any(line.get("grand_potential_intercept_eV") is None for line in minima):
        # oxygen_reference_mode='none' intentionally has no absolute vacancy
        # formation free energy across different oxygen contents.
        return outputs

    grouped: dict[tuple[tuple[tuple[str, int], ...], int], list[dict[str, Any]]] = {}
    for line in minima:
        grouped.setdefault(_composition_identity(line), []).append(line)

    pressure_rows: list[dict[str, Any]] = []
    free_energy_rows: list[dict[str, Any]] = []
    pressure_is_approximate = bool(
        cfg.pressure_mapping and cfg.oxygen_standard_state_mode == "none"
    )
    if cfg.oxygen_standard_state_mode == "nist_shomate":
        standard_state_source = NIST_O2_SHOMATE_SOURCE
    elif cfg.oxygen_standard_state_mode == "user_table":
        standard_state_source = "user-supplied table"
    else:
        standard_state_source = None

    if cfg.pressure_mapping:
        for identity in sorted(grouped):
            lines = sorted(grouped[identity], key=lambda row: int(row["n_vacancies"]))
            for temperature in cfg.temperatures_K:
                temperature = float(temperature)
                standard_delta = _standard_state_delta_mu(
                    cfg, temperature, calibrated=calibrated_reference
                )
                solid_terms = {
                    int(line["n_vacancies"]): solid_configurational_thermodynamics(
                        mode,
                        rows,
                        line,
                        temperature,
                        exclude_unconverged=bool(cfg.exclude_unconverged),
                    )
                    for line in lines
                }
                for log10_pressure in _pressure_grid(cfg):
                    pressure = 10.0**log10_pressure
                    pressure_delta = oxygen_pressure_delta_mu_eV_per_O(
                        temperature,
                        pressure,
                        cfg.standard_oxygen_pressure_bar,
                    )
                    total_delta = standard_delta + pressure_delta
                    static_values: dict[int, float] = {}
                    finite_values: dict[int, float] = {}
                    for line in lines:
                        n_vacancies = int(line["n_vacancies"])
                        static_value = (
                            float(line["grand_potential_intercept_eV"])
                            + n_vacancies * total_delta
                        )
                        static_values[n_vacancies] = static_value
                        finite_values[n_vacancies] = (
                            static_value
                            + float(solid_terms[n_vacancies]["free_energy_correction_eV"])
                        )

                    tied = _tied_counts(
                        finite_values, float(cfg.thermodynamic_tolerance_eV)
                    )
                    representative = next(
                        line for line in lines if int(line["n_vacancies"]) == tied[0]
                    )
                    representative_term = solid_terms[tied[0]]
                    pressure_rows.append(
                        {
                            **representative,
                            "temperature_K": temperature,
                            "oxygen_partial_pressure_bar": pressure,
                            "log10_oxygen_partial_pressure_bar": log10_pressure,
                            "standard_oxygen_pressure_bar": cfg.standard_oxygen_pressure_bar,
                            "delta_mu_O_standard_eV_per_O": standard_delta,
                            "delta_mu_O_pressure_eV_per_O": pressure_delta,
                            "delta_mu_O_total_eV_per_O": total_delta,
                            "best_n_vacancies": tied[0] if len(tied) == 1 else None,
                            "best_vacancy_percent": (
                                representative["vacancy_percent_of_parent_oxygen"]
                                if len(tied) == 1
                                else None
                            ),
                            "best_vacancies_per_cation": (
                                representative["vacancies_per_cation"]
                                if len(tied) == 1
                                else None
                            ),
                            "minimum_static_grand_potential_eV": min(static_values.values()),
                            "minimum_finite_T_grand_potential_eV": min(finite_values.values()),
                            "solid_configurational_free_energy_correction_eV": (
                                representative_term["free_energy_correction_eV"]
                            ),
                            "solid_configurational_entropy_eV_per_K": (
                                representative_term["entropy_eV_per_K"]
                            ),
                            "configurational_partition_energy_basis": (
                                representative_term["partition_energy_basis"]
                            ),
                            "configurational_partition_orbit_count": (
                                representative_term["partition_orbit_count"]
                            ),
                            "configurational_partition_total_degeneracy": (
                                representative_term["partition_total_degeneracy"]
                            ),
                            "configurational_partition_exact": (
                                representative_term["partition_exact"]
                            ),
                            "solid_configurational_entropy_applied": mode != "none",
                            "is_tied": len(tied) > 1,
                            "tied_n_vacancies": tied,
                            "pressure_mapping_is_approximate": pressure_is_approximate,
                            "pressure_mapping_approximation": (
                                "O2 standard-state thermal correction omitted"
                                if pressure_is_approximate
                                else (
                                    "calibrated 298 K enthalpy reference + gas thermochemistry"
                                    if calibrated_reference
                                    else "gas standard-state thermochemistry + ideal-gas pressure"
                                )
                            ),
                            "oxygen_standard_state_mode": cfg.oxygen_standard_state_mode,
                            "oxygen_standard_state_source": standard_state_source,
                            "oxygen_standard_state_enthalpy_origin_K": (
                                298.15
                                if calibrated_reference
                                and cfg.oxygen_standard_state_mode == "nist_shomate"
                                else None
                            ),
                            "oxygen_standard_state_zpe_included": False,
                        }
                    )

                    for line in lines:
                        n_vacancies = int(line["n_vacancies"])
                        term = solid_terms[n_vacancies]
                        formation_free_energy = finite_values[n_vacancies]
                        free_energy_rows.append(
                            {
                                **line,
                                "temperature_K": temperature,
                                "oxygen_partial_pressure_bar": pressure,
                                "log10_oxygen_partial_pressure_bar": log10_pressure,
                                "standard_oxygen_pressure_bar": cfg.standard_oxygen_pressure_bar,
                                "delta_mu_O_standard_eV_per_O": standard_delta,
                                "delta_mu_O_pressure_eV_per_O": pressure_delta,
                                "delta_mu_O_total_eV_per_O": total_delta,
                                "vacancy_formation_energy_static_reference_eV": float(
                                    line["grand_potential_intercept_eV"]
                                ),
                                "oxygen_thermal_pressure_contribution_eV": (
                                    n_vacancies * total_delta
                                ),
                                "solid_configurational_free_energy_correction_eV": term[
                                    "free_energy_correction_eV"
                                ],
                                "solid_configurational_entropy_eV_per_K": term[
                                    "entropy_eV_per_K"
                                ],
                                "vacancy_formation_free_energy_eV": formation_free_energy,
                                "vacancy_formation_free_energy_per_vacancy_eV": (
                                    formation_free_energy / n_vacancies
                                    if n_vacancies
                                    else None
                                ),
                                "configurational_partition_mean_relative_energy_eV": term[
                                    "mean_relative_energy_eV"
                                ],
                                "configurational_partition_log_Z_relative": term[
                                    "partition_log_Z_relative"
                                ],
                                "configurational_partition_energy_basis": term[
                                    "partition_energy_basis"
                                ],
                                "configurational_partition_orbit_count": term[
                                    "partition_orbit_count"
                                ],
                                "configurational_partition_total_degeneracy": term[
                                    "partition_total_degeneracy"
                                ],
                                "configurational_partition_exact": term[
                                    "partition_exact"
                                ],
                                "solid_configurational_entropy_applied": mode != "none",
                                "oxygen_standard_state_mode": cfg.oxygen_standard_state_mode,
                                "oxygen_standard_state_source": standard_state_source,
                                "oxygen_standard_state_zpe_included": False,
                            }
                        )

    pressure_csv, pressure_json = _write_pair(
        parent_root, "vacancy_static_pressure_map", pressure_rows
    )
    outputs["vacancy_static_pressure_map_csv"] = pressure_csv
    outputs["vacancy_static_pressure_map_json"] = pressure_json
    free_csv, free_json = _write_pair(
        parent_root, "vacancy_formation_free_energy", free_energy_rows
    )
    outputs["vacancy_formation_free_energy_csv"] = free_csv
    outputs["vacancy_formation_free_energy_json"] = free_json

    neglected = list(NEGLECTED_SOLID_TERMS)
    if mode != "none" and "configurational" in neglected:
        neglected.remove("configurational")
    applied_outputs = (
        ["vacancy_static_pressure_map", "vacancy_formation_free_energy"]
        if mode != "none"
        else []
    )
    for metadata_key in ("metadata", "static_metadata"):
        metadata_path = outputs.get(metadata_key)
        if metadata_path is None or not metadata_path.exists():
            continue
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        if mode != "none":
            metadata["static_lattice_approximation"] = approximation
        metadata.update(
            {
                "solid_configurational_entropy": mode,
                "configurational_entropy_applied_to": applied_outputs,
                "configurational_partition_requires_exact_degeneracy": (
                    mode == "configurational"
                ),
                "configurational_partition_energy_strategy": (
                    "complete exact relaxed spectrum when available; otherwise complete "
                    "exact single-point spectrum correction relative to its minimum, added "
                    "to the relaxed static minimum"
                    if mode == "configurational"
                    else None
                ),
                "finite_temperature_vacancy_free_energy_output": str(free_json),
                "neglected_solid_terms": neglected,
                "pressure_mapping_is_approximate": pressure_is_approximate,
            }
        )
        metadata_path.write_text(
            json.dumps(metadata, indent=2, sort_keys=True), encoding="utf-8"
        )

    return outputs


__all__ = [
    "augment_vacancy_formation_free_energy",
    "configurational_partition_thermodynamics",
    "ideal_vacancy_configurational_entropy_eV_per_K",
    "solid_configurational_thermodynamics",
]
